FROM ubuntu:precise

MAINTAINER Rizky Maulana Nugraha<rizky@kartoza.com>

RUN echo "deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu precise main" >> /etc/apt/sources.list
RUN apt-get -qq -y update
RUN apt-get install -y --force-yes \
    build-essential \
    xvfb \
    x-ttcidfont-conf \
    xfonts-100dpi \
    xfonts-75dpi \
    xfonts-scalable \
    xfonts-cyrillic \
    git \
    python-pip \
    xvfb \
    python-nose \
    python-coverage \
    pyflakes \
    python-nosexcover \
    python-scientific \
    python-dev \
    qgis \
    python-qgis
RUN pip install coverage
RUN pip install nosexcover
RUN pip install nose
RUN pip install beautifulsoup
RUN pip install --upgrade pip
RUN pip install --upgrade pep8
RUN pip install --upgrade pylint
RUN pip install --upgrade numpy
RUN pip install scrutinizer-ocular


RUN export QGIS_PREFIX_PATH=/usr
RUN export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
RUN echo "PYTHONPATH:" $PYTHONPATH
RUN export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

# This section taken on 2 July 2015 from
# https://docs.docker.com/examples/running_ssh_service/
# Sudo is needed by pycharm when it tries to pip install packages
RUN apt-get update && apt-get install -y openssh-server sudo
RUN mkdir /var/run/sshd
RUN echo 'root:docker' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# Open port 22 as we will be using a remote interpreter from pycharm
EXPOSE 22

# End of cut & paste section

# Mount inasafe and insafe_data under /

ADD run-test.sh /run-test.sh
ADD startup.sh /startup.sh
RUN chmod +x /run-test.sh
RUN mkdir -p /home/test/inasafe
WORKDIR /home/test/inasafe
RUN echo "export DISPLAY=:99" >> ~/.bashrc
RUN echo "source /home/test/inasafe/run-env-linux.sh /usr" >> ~/.bashrc

#ENTRYPOINT ["make"]


# Here we list packages to test by default
#CMD ["safe_qgis"]
#CMD ["/run-test.sh"]
CMD ["/startup.sh"]
